# Generated by Django 5.0.1 on 2024-02-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='links',
            field=models.URLField(default='www.google.com'),
        ),
    ]
