# Generated by Django 5.0.1 on 2024-02-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='links',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
